spring:
  application:
    name: etudiant-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}

logging:
  level:
    org:
      hibernate:
        type: debug
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug
    com:
      openclassrooms:
        etudiant: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'